name: install-org
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        repository: tarsiiformes/org
        ref: texinfo-cmds_tmp
        path: org
    - run: git tag -a -m dummy release_9999
      shell: bash
      working-directory: org
    - run: touch local.mk
      shell: bash
      working-directory: org
    - run: make autoloads
      shell: bash
      working-directory: org
